package main

// DO NOT EDIT, this file is generated by hover at compile-time for the serial_port_flutter plugin.

import (
	flutter "github.com/go-flutter-desktop/go-flutter"
	serial_port_flutter "github.com/pstwh/serial_port_flutter/go"
)

func init() {
	// Only the init function can be tweaked by plugin maker.
	options = append(options, flutter.AddPlugin(&serial_port_flutter.SerialPortFlutterPlugin{}))
}
